myApp/urls.py
from django.urls import path
from . import views

app_name = 'myApp'

urlpatterns = [
    path('',views.user_login,name = 'user_login'),#登陆页和主页
    path('logout/',views.user_logout,name = 'user_logout'),#退出
    path('stuHome/',views.stu_home,name = 'stu_home'),#学生主页
    path('teaHome/',views.tea_home,name = 'tea_home'),#老师主页
    path('teaHome/tea_self_center/',views.tea_self_center,name = 'tea_self_center'),#老师个人中心
    path('stuHome/stu_self_center/',views.stu_self_center,name = 'stu_self_center'),#学生个人中心
    #path('stuHome/stu_self_center/stu_edit_profile',views.stu_edit_profile,name = 'stu_edit_profile'),#学生信息编辑
    #path('stuHome/tea_self_center/tea_edit_profile',views.tea_edit_profile,name = 'tea_edit_profile'),#老师信息编辑
    path('stuHome/stu_grade',views.stu_grade,name = 'stu_grade'),#学生所属班级
    path('teaHome/tea_grade',views.tea_grade,name = 'tea_grade'),#老师教学班级
    path('stuHome/leave',views.leave,name = 'leave'),#请假信息
    path('teaHome/leave_manage',views.leave_manage,name = 'leave_manage'),#请假管理
    path('stuHome/leave_history',views.leave_history,name = 'leave_history')#请假记录

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myApp.urls')),
    path('comment/',include('comment.urls'))
]

myApp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class Teacher(models.Model):
    #db_column为数据库表头名，verbose_name为后台页面列表中显示的字段名
    teacher = models.OneToOneField(User,default="",on_delete=models.CASCADE,verbose_name='用户')
    tname = models.CharField(max_length=20,db_column='名字',verbose_name='名字')
    tgender = models.BooleanField(default=True,db_column='性别',verbose_name='性别')
    tid = models.CharField(max_length=20,db_column='职工号',verbose_name='职工号')
    isDelete = models.BooleanField(db_column='是否删除',default=False)

    def __str__(self):
        return "%s-%s"%(self.tname,self.tid)
    #元选项
    class Meta:
        db_table = 'teachers'
        ordering = ['id']

class Grade(models.Model):
    gname = models.CharField(max_length=20,db_column='班级名',verbose_name='班级名')
    gdate = models.DateTimeField(db_column='创建时间',verbose_name='创建时间')
    gnum = models.IntegerField(db_column='班级人数',verbose_name='班级人数')
    ggirlnum = models.IntegerField(db_column='女生人数',verbose_name='女生人数')
    gboynum = models.IntegerField(db_column='男生人数',verbose_name='男生人数')
    isDelete = models.BooleanField(db_column='是否删除',default=False)
    gteacher = models.ForeignKey(Teacher,related_name='teacher_grade',on_delete=models.CASCADE,verbose_name='老师')

    def __str__(self):
        return "%s"%(self.gname)
    lastTime = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'grades'
        ordering = ['id']

class Student(models.Model):
    student = models.OneToOneField(User,default='',on_delete=models.CASCADE)
    verbose_name = '学生'
    sname = models.CharField(max_length=20,db_column='名字',verbose_name='名字')
    sgender = models.BooleanField(default=True,db_column='性别',verbose_name='性别')
    sid = models.CharField(max_length=20,db_column='学号',verbose_name='学号')
    smajor = models.CharField(default='',max_length=20,db_column='专业',verbose_name='专业')
    sgrade = models.ManyToManyField("Grade",verbose_name='班级')
    isDelete = models.BooleanField(db_column='是否删除',default=False)

    def __str__(self):
        return "%s-%s"%(self.sname,self.sid)

    class Meta:
        db_table = 'students'
        ordering = ['id']

myApp/forms.py
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django import forms
from django.contrib.auth.models import User

class Stu_edit_form(UserChangeForm):
    name = forms.CharField(required=False,max_length=50)

    class Meta:
        model = User
        fields = ("email","username","name",'password')

myApp/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth.decorators import login_required
from .models import*
from comment.models import*
from .forms import*



#登陆和主页
def user_login(request):
    if request.method == 'POST':
        user = authenticate(request,username = request.POST['user_name'],
                            password = request.POST['pwd'])
        if user is not None:
            login(request, user)
            if request.POST['type'] == '0':
                name = request.user.teacher.tname  # 查询当前用户的老师名
                tea = Teacher.objects.filter(tname=name).first()  # 查询出该老师
                gender = tea.tgender
                return render(request, 'myApp/老师个人中心.html', {"name": name, 'gender': gender})
            elif request.POST['type'] == '1':
                name = request.user.student.sname  # 查询当前用户的学生名
                stu = Student.objects.filter(sname=name).first()  # 查询出该学生
                gender = stu.sgender
                return render(request, 'myApp/学生个人中心.html', {"name": name, 'gender': gender})
            elif request.POST['type'] == False:
                return render(request, 'myApp/首页登陆.html', {'error': '尚未选择学生或老师'})
        else:
            return render(request, 'myApp/首页登陆.html', {'error': '用户名或密码错误'})

    else:
        return render(request,'myApp/首页登陆.html')

#登出
def user_logout(request):
    if request.method == 'POST':
        user = authenticate(request,username = request.POST['user_name'],
                            password = request.POST['pwd'])
        if user is not None:
            login(request, user)
            if request.POST['type'] == '0':
                name = request.user.teacher.tname  # 查询当前用户的老师名
                tea = Teacher.objects.filter(tname=name).first()  # 查询出该老师
                gender = tea.tgender
                return render(request, 'myApp/老师个人中心.html', {"name": name, 'gender': gender})
            elif request.POST['type'] == '1':
                name = request.user.student.sname  # 查询当前用户的学生名
                stu = Student.objects.filter(sname=name).first()  # 查询出该学生
                gender = stu.sgender
                return render(request, 'myApp/学生个人中心.html', {"name": name, 'gender': gender})
        else:
            return render(request, 'myApp/首页登陆.html', {'error': "用户名或密码错误"})
    return render(request,'myApp/首页登陆.html')

#老师主页
@login_required(login_url = "myApp:login")
def tea_home(request):
    return render(request, 'myApp/老师主页.html')

#老师个人中心
@login_required(login_url = "myApp:login")
def tea_self_center(request):
    name = request.user.teacher.tname  # 查询当前用户的老师名
    tea = Teacher.objects.filter(tname=name).first()  # 查询出该老师
    gender = tea.tgender
    return render(request, 'myApp/老师个人中心.html', {"name": name, 'gender': gender})

#学生个人中心
@login_required(login_url = "myApp:login")
def stu_self_center(request):
    name = request.user.student.sname  # 查询当前用户的学生名
    stu = Student.objects.filter(sname=name).first()  # 查询出该学生
    gender = stu.sgender
    return render(request, 'myApp/学生个人中心.html',{"name":name,'gender':gender})


#学生主页
@login_required(login_url = "myApp:login")
def stu_home(request):
    name = request.user.student.sname  # 查询当前用户的学生名
    return render(request, 'myApp/学生个人中心.html', {"name":name,})


#老师信息编辑
'''
@login_required(login_url = "myApp:login")
def tea_edit_profile(request):
    if request.method == 'POST':
        edit_form = Stu_edit_form(request.POST)
        if edit_form.is_valid():
            edit_form.save()
            user = authenticate(username=edit_form.cleaned_data['username'],password=edit_form.cleaned_data['password1'])
            login(request,user)
            return redirect('myApp:学生主页')
    else:
        edit_form = Stu_edit_form(instance = request.user)

    content = {'edit_form':edit_form}
    #if request.method == 'POST':
    return render(request, 'myApp/老师信息编辑.html',content)
'''

#学生的班级
@login_required(login_url = "myApp:login")
def stu_grade(request):
    name = request.user.student.sname#查询当前用户的学生名
    stu = Student.objects.filter(sname = name).first()#查询出该学生
    my_grades = stu.sgrade.all()#查询出该学生关联的所有班级
    return render(request,'myApp/学生的班级.html',{'name':name,'grades':my_grades})

#老师的班级
@login_required(login_url = "myApp:login")
def tea_grade(request):
    name = request.user.teacher.tname#查询当前用户的老师名
    tea = Teacher.objects.filter(tname = name).first()#查询出该老师
    tea_grades = tea.teacher_grade.all()#查询出该老师关联的所有班级
    return render(request,'myApp/老师的班级.html',{'grades':tea_grades,'name':name})

#请假信息
@login_required(login_url = "myApp:login")
def leave(request):
    stu_name = request.user.student.sname
    obj = Student.objects.filter(sname = stu_name).first()
    stu_grades = obj.sgrade.all()
    if request.method == 'POST':
        grade_name = request.POST['grade']
        text = request.POST['text']
        grade = Grade.objects.get(gname=grade_name)  # 找到数据库中对应的班级
        jiatiao = Comment(grade=grade, stu=stu_name, body=text, created='',is_agree='')
        jiatiao.save()
    return render(request,'myApp/请假信息.html',{'grades':stu_grades,'name':stu_name})

#请假管理
@login_required(login_url = "myApp:login")
def leave_manage(request):
    name = request.user.teacher.tname  # 查询当前用户的老师名
    tea = Teacher.objects.filter(tname=name).first()  # 查询出该老师
    tea_grades = tea.teacher_grade.all()  # 查询出该老师关联的所有班级
    comments = []
    for grade in tea_grades:#每个班级的请假条
        comments = grade.grade_comment.all()
    if request.method == 'POST':
        if request.POST['is_agree'] == '0':
            jiatiao = Comment.objects.filter(body = request.POST['jiatiao']).first()
            jiatiao.is_agree = False
            jiatiao.save()
        elif request.POST['is_agree'] == '1':
            print(1)
            jiatiao = Comment.objects.filter(body=request.POST['jiatiao']).first()
            jiatiao.is_agree = True
            jiatiao.save()
    return render(request, 'myApp/请假管理.html',{'comments':comments,'name':name})

@login_required(login_url = "myApp:login")
def leave_history(request):
    name = request.user.student.sname  # 获取当前用户的学生姓名
    jiatiao = Comment.objects.filter(stu = name).all()
    return render(request, 'myApp/请假记录.html', {"comment": jiatiao, 'name': name})

templates/myApp/学生个人中心.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>个人中心</title>
    <!--Bootstrape Css-->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel = "stylesheet" type = "text/css" href = "{% static '总样式.css' %}">
</head>
<body>
    <nav class="navbar navbar-dark bg-primary fixed-top navbar-expand-lg topnav">
        <h1 class="navbar-brand">请假系统</h1>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto" style = "float: top;">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'myApp:stu_self_center' %}">个人中心<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myApp:leave_history' %}">请假记录</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myApp:stu_grade' %}">我的班级<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myApp:leave' %}">请假</a>
                </li>
                </ul>
        </div>
        <a class="nav-link logout" href="{% url 'myApp:stu_self_center' %}"><p><font color ="white">{{ name }}</font></p></a>
        <a class="nav-link logout" href="{% url 'myApp:user_logout' %}" title="退出"><p><font color = "white">退出登录</font></p></a>
    </nav>
    <div id = "background"></div>

    <form action="" method="post">
    <div class="card stdmsg_center_article"  id = "std_card">
        <br>
        <br><br><br>
        <img class="card-img-top" src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1560339550404&di=2ac9a973306a9f9a37c37d3e7f21ca3d&imgtype=0&src=http%3A%2F%2Fimg.qqzhi.com%2Fuploads%2F2019-02-28%2F093551547.jpg" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">个人信息</h5>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">账号：{{ user.username }}</li>
            <li class="list-group-item">邮箱：{{ user.email }}</li>
            <li class="list-group-item">姓名：{{ name }}</li>
            {% if gender == True %}
                <li class="list-group-item">性别：男</li>
                {% elif gender == False %}
                <li class="list-group-item">性别：女</li>
            {% endif %}
            <li class="list-group-item">学号：{{ user.username }}</li>
        </ul>
    </div>

    <nav class="navbar fixed-bottom navbar-light navbar-dark bg-primary">
        <a class="navbar-brand" href="#">感谢使用</a>
    </nav>

    <!--Bootstrape Js-->
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/myApp/学生信息编辑.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人信息编辑</title>
</head>
<body>
    <div align="right">
        <a href="{% url 'myApp:stu_self_center' %}">返回个人中心</a>
        <a href="{% url 'myApp:stu_home' %}">返回主页</a>
        <a href="{% url 'myApp:user_logout' %}" title="退出">退出</a>
    </div>
    <center>
        <font size="100">&lt;请&nbsp;假&nbsp;系&nbsp;统&gt;</font>
        <br>
        <br>
        <br>
        <br>
    </center>
        <h1>编辑信息</h1>
        <br>
        <form action="" method="post">
            {% csrf_token %}
            {{ edited_form.as_p }}
            <br>
            <div>
                <button type="submit">提交</button>
            </div>
            <br>
        </form>
</body>
</html>

templates/myApp/学生的班级.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>我的班级</title>
    <!--Bootstrape Css-->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel = "stylesheet" type = "text/css" href = "{% static '总样式.css' %}">
</head>
<body>
    <nav class="navbar navbar-dark bg-primary fixed-top navbar-expand-lg topnav">
        <h1 class="navbar-brand">请假系统</h1>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto" style = "float: top;">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myApp:stu_self_center' %}">个人中心</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myApp:leave_history' %}">请假记录</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'myApp:stu_grade' %}">我的班级<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myApp:leave' %}">请假</a>
                </li>

            </ul>
        </div>
        <a class="nav-link logout" href="{% url 'myApp:stu_self_center' %}"><p><font color ="white">{{ name }}</font></p></a>
        <a class="nav-link logout" href="{% url 'myApp:user_logout' %}" title="退出"><p><font color = "white">退出登录</font></p></a>
    </nav>
    <div id = "background"></div>

    <div class="card stdmsg_center_article"  id = "std_card">
        <br>
        <br><br><br>
        <div class="card-body">
            <h5 class="card-title">本学期的班级</h5>
        </div>
        <ul class="list-group list-group-flush">
            {% for grade in grades %}
            <li class="list-group-item">{{ grade.gname }} ———————— {{ grade.gteacher }}</li>
            {% endfor %}
        </ul>
    </div>

    <nav class="navbar fixed-bottom navbar-light navbar-dark bg-primary">
        <a class="navbar-brand" href="#">感谢使用</a>
    </nav>

    <!--Bootstrape Js-->
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/myApp/老师主页.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>老师主页</title>
</head>
<body>
    <center>
    <font size="100">&lt;请&nbsp;假&nbsp;系&nbsp;统&gt;</font>
    </center>
    <div align="right">
        <a href="{% url 'myApp:user_logout' %}" title="退出">退出登陆</a>
        </div>
    <ul>
        <li><a href="{% url 'myApp:tea_self_center' %}">个人中心</a></li>
        <li><a href="{% url 'myApp:tea_grade' %}">我的班级</a></li>
        <li><a href="{% url 'myApp:leave_manage' %}">请假管理</a></li>
        <li><a href="#">请假记录</a></li>
        <li><a href="#">我的消息</a></li>
    </ul>
</body>
</html>

templates/myApp/请假信息.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>请假</title>
    <!--Bootstrape Css-->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel = "stylesheet" type = "text/css" href = "{% static '总样式.css' %}">
    <script>
        function alert_display() {
            alert("提交成功");
        }
    </script>
</head>
<body>
    <nav class="navbar navbar-dark bg-primary fixed-top navbar-expand-lg topnav">
        <h1 class="navbar-brand">请假系统</h1>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myApp:stu_self_center' %}">个人中心</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myApp:leave_history' %}">请假记录</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myApp:stu_grade' %}">我的班级<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'myApp:leave' %}">请假<span class="sr-only">(current)</span></a>
                </li>
                </ul>
        </div>
        <a class="nav-link logout" href="{% url 'myApp:stu_self_center' %}"><p><font color ="white">{{ name }}</font></p></a>
        <a class="nav-link logout" href="{% url 'myApp:user_logout' %}" title="退出"><p font = "color:white;"><font color = "white">退出登录</font></p></a>
    </nav>
    <div id = "background"><br><br><br><br></div>

    <div class = "stdmsg_center_article">
        <br>
        <h2>填写假条</h2>
        <form id = "center_form" action="#" method="POST">
            {% csrf_token %}
                <label for="" >请假班级：</label>
                <select name="grade">
                {% for grade in grades %}
                    <option value="{{ grade.gname }}">
                    <a href="#">{{ grade.gname }} &nbsp;&nbsp;&nbsp;{{ grade.gteacher }}</a>
                    </option>
                {% endfor %}
                </select>
                    <br>
                    <textarea id="comment_text" name="text" cols="60" rows="20"></textarea>
                    <br>
                    <button type="Submit" class="btn btn-primary btn-lg" id = "button_sub" onclick="alert_display()">提交</button>
            {{ error }}
        </form>
    </div>

    <nav class="navbar fixed-bottom navbar-light navbar-dark bg-primary">
        <a class="navbar-brand" href="">感谢使用，这里什么都没有哦</a>
    </nav>

    <!--Bootstrape Js-->
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/myApp/请假记录.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>请假记录</title>
    <!--Bootstrape Css-->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel = "stylesheet" type = "text/css" href = "{% static '总样式.css' %}">
</head>
<body>
    <nav class="navbar navbar-dark bg-primary fixed-top navbar-expand-lg topnav">
        <h1 class="navbar-brand">请假系统</h1>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myApp:stu_self_center' %}">个人中心<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'myApp:leave_history' %}">请假记录</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link" href="{% url 'myApp:stu_grade' %}">我的班级<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myApp:leave' %}">请假</a>
                </li>
            </ul>
        </div>
        <a class="nav-link logout" href="{% url 'myApp:stu_self_center' %}"><p><font color ="white">{{ name }}</font></p></a>
        <a class="nav-link logout" href="{% url 'myApp:user_logout' %}" title="退出"><p><font color = "white">退出登录</font></p></a>
    </nav>
    <div id = "background"><br><br><br><br>

    <div class = "stdmsg_center_article">
        <div>
            <br>
            <h2 id = "jiatiao_top">请假记录</h2>
            <ul>
                {% for i in comment %}
                    <li class = "jiatiao">
                        <h3>{{ i.grade }}</h3>
                        <p>&nbsp;&nbsp;&nbsp;&nbsp;{{ i.body }}</p>
                        <p class = "jiatiao_stdname">------{{ i.stu }}</p>
                        {% if i.is_agree == True %}
                            <p>已同意</p>
                        {% elif i.is_agree == False %}
                            <p>已拒绝</p>
                        {% elif i.is_agree == None %}
                            <p>暂未处理</p>
                        {% endif %}
                        <p>{{ i.created }}</p>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <nav class="navbar fixed-bottom navbar-light navbar-dark bg-primary">
        <a class="navbar-brand" href="#jiati  ao_top">感谢使用，点我返回顶部</a>
    </nav>

    <!--Bootstrape Js-->
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.bootcss.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>